* jsgames

My playground repo for building simple Javascript Games.

I try to keep an updated repo available here whenever I change something: http://img.failar.nu/etu/.jsgames/

** Table of Contents of repo

*** goblin/ - Capture the goblin
goblin/ is in the base a pure copy of this tutorial: [[http://www.lostdecadegames.com/how-to-make-a-simple-html5-canvas-game/]]

**** With following modifications:
- You can't walk outside of the canvas
- The players position doesn't reset when the goblin is captured
- The goblin moves away from the player, but does't understand corners or have any "smart AI" at all.

I won't do anything more with this.

*** jumper/ - Jump on platforms
jumper/ is based on this tutorial: http://michalbe.blogspot.se/2010/09/simple-game-with-html5-canvas-part-1.html

**** With following modifications:
- I haven't implemented scrolling, at all.
- The platforms does not appear at random and does have collision detection from bottom and the sides
- Implemented falling of platforms better
- My clouds moves at different speed depending on their size to make a fake-3d-feeling-effect

This could be a fairly simple platformer game without too much modifications, but I didn't bother. I won't do anything more with this, and if I would, I would start from the beginning.

*** nyancat/ - Nyancat space shooter
nyancat/ is what I think I want to keep working on for a while, I started it from scratch, with inspiration of the tutorials used for game_01/ and game_02/, but decided to do everything my own way :)

It's going to be a Nyancat shooter game in space.

**** To Implement
- Implement things to collide with
- Implement collisiondetection for things to collide with and for projectiles

**** Already done
- Implemented space with stars moving at different speed
- Implemented player with animated nyancat
- Implemented basic projectiles so the cat can shoot (but got nothing to hit (so far!))
- Implemented controlls for the cat (Up, Down, Space)
- Implemented monsters
- Implemented that you can kill monsters
- Implemented that monsters can kill you
- Implemented score of some kind
- Added graphics for monsters, it's spaceinvaders in 4 different colors!
- Monsters shoot and they will kill you
- Added Hidden "Insane Mode"
- Implemented progression to make the game harder over time
- Added input type number where user can enter desired fps
- When you shoot a monster, the projectile will dissapear on hit
- You gain 2 health every level up

**** Insane Mode
Fire up a JS-Console and type:
: gameState.insane = true

And just hit enter, then you will notice that monsters spawn more often, like when you kill one or it despawns, it will also decrease their shooting cooldown :-)

